### PR TITLE
Bump cosign, fix breakage

### LINKED ISSUE #713: Fails when upgrading to 1.18
The http://github.com/ossf/scorecard project uses `ko` and we are in the process of upgrading to `1.18`. `ko` seems to have issues while upgrading to `1.18` https://github.com/ossf/scorecard/runs/6632670453?check_suite_focus=true#step:8:77

Any help would be appreciated.

Thanks

### PR DESCRIPTION
**Pull request by imjasonh**
```
$ go get -u github.com/sigstore/cosign
go get -u github.com/sigstore/cosign@latest
go: downloading github.com/sigstore/cosign v1.8.0
go: upgraded github.com/sigstore/cosign v1.3.2-0.20211120003522-90e2dcfe7b92 => v1.8.0
$ go get ./...
$ go mod tidy
$ go mod vendor
$ go build ./...
# github.com/google/ko/pkg/build
pkg/build/gobuild.go:351:20: undefined: types.CycloneDXMediaType
```

The const got renamed some time between 1.3.1 and 1.8.0: https://pkg.go.dev/github.com/sigstore/cosign@v1.8.0/pkg/types

Fixes #713 

Notably, some time between 1.3.1 and 1.8.0, the vendored cosign dependency seems to have grown by ~180k lines... 😒

### CODE REVIEW

**Comment by imjasonh** [comment]
Superceded by https://github.com/google/ko/pull/667 which bumps even more deps.
